# Description:
#  After successful deploy show octodex
#
# Dependencies:
#  None
#
# Configuration:
#  None
#
# Comands:
#  finished deploying - Reply with octodex
#
# Author:
#  skibish

module.exports = (robot) ->
  robot.hear /(finished deploying)|(Finish gw2:deploy_code)/i, (msg) ->
    msg.send msg.random octodex

  robot.hear /(cancelled deployment)|(failed deployment)/i, (msg) ->
    msg.reply "http://storage1.censor.net.ua/images/e/7/2/e/e72e8d4eb4f83a233d3b4e188f22f02f/original.jpg"

octodex = [
  "https://octodex.github.com/images/saritocat.png",
  "https://octodex.github.com/images/topguntocat.png",
  "https://octodex.github.com/images/carlostocat.gif",
  "https://octodex.github.com/images/grinchtocat.gif",
  "https://octodex.github.com/images/maxtocat.gif",
  "https://octodex.github.com/images/yaktocat.png",
  "https://octodex.github.com/images/steroidtocat.png",
  "https://octodex.github.com/images/mummytocat.gif",
  "https://octodex.github.com/images/labtocat.png",
  "https://octodex.github.com/images/dunetocat.png",
  "https://octodex.github.com/images/octoliberty.png",
  "https://octodex.github.com/images/femalecodertocat.png",
  "https://octodex.github.com/images/daftpunktocat-thomas.gif",
  "https://octodex.github.com/images/daftpunktocat-guy.gif",
  "https://octodex.github.com/images/foundingfather_v2.png",
  "https://octodex.github.com/images/poptocat_v2.png",
  "https://octodex.github.com/images/Mardigrastocat.png",
  "https://octodex.github.com/images/kimonotocat.png",
  "https://octodex.github.com/images/Professortocat_v2.png",
  "https://octodex.github.com/images/goretocat.png",
  "https://octodex.github.com/images/Robotocat.png",
  "https://octodex.github.com/images/motherhubbertocat.png",
  "https://octodex.github.com/images/skitchtocat.png",
  "https://octodex.github.com/images/gangnamtocat.png",
  "https://octodex.github.com/images/droctocat.png",
  "https://octodex.github.com/images/spidertocat.png",
  "https://octodex.github.com/images/megacat-2.png",
  "https://octodex.github.com/images/dodgetocat_v2.png",
  "https://octodex.github.com/images/stormtroopocat.png",
  "https://octodex.github.com/images/pusheencat.png",
  "https://octodex.github.com/images/murakamicat.png",
  "https://octodex.github.com/images/homercat.png",
  "https://octodex.github.com/images/minion.png",
  "https://octodex.github.com/images/droidtocat.png",
  "https://octodex.github.com/images/octofez.png",
  "https://octodex.github.com/images/heisencat.png",
  "https://octodex.github.com/images/red-polo.png",
  "https://octodex.github.com/images/twenty-percent-cooler-octocat.png",
  "https://octodex.github.com/images/momtocat.png",
  "https://octodex.github.com/images/front-end-conftocat.png",
  "https://octodex.github.com/images/snowoctocat.png",
  "https://octodex.github.com/images/electrocat.png",
  "https://octodex.github.com/images/codercat.jpg",
  "https://octodex.github.com/images/strongbadtocat.png",
  "https://octodex.github.com/images/adventure-cat.png",
  "https://octodex.github.com/images/doctocat-brown.jpg",
  "https://octodex.github.com/images/dojocat.jpg",
  "https://octodex.github.com/images/defunktocat.png",
  "https://octodex.github.com/images/herme-t-crabb.png",
  "https://octodex.github.com/images/saint-nicktocat.jpg",
  "https://octodex.github.com/images/orderedlistocat.png",
  "https://octodex.github.com/images/thanktocat.png",
  "https://octodex.github.com/images/megacat.jpg",
  "https://octodex.github.com/images/linktocat.jpg",
  "https://octodex.github.com/images/plumber.jpg",
  "https://octodex.github.com/images/octotron.jpg",
  "https://octodex.github.com/images/baracktocat.jpg",
  "https://octodex.github.com/images/octocat-de-los-muertos.jpg",
  "https://octodex.github.com/images/grim-repo.jpg",
  "https://octodex.github.com/images/father_timeout.jpg",
  "https://octodex.github.com/images/waldocat.png",
  "https://octodex.github.com/images/hipster-partycat.jpg",
  "https://octodex.github.com/images/riddlocat.png",
  "https://octodex.github.com/images/visionary.jpg",
  "https://octodex.github.com/images/oktobercat.png",
  "https://octodex.github.com/images/shoptocat.png",
  "https://octodex.github.com/images/nyantocat.gif",
  "https://octodex.github.com/images/octdrey-catburn.jpg",
  "https://octodex.github.com/images/spectrocat.png",
  "https://octodex.github.com/images/bear-cavalry.png",
  "https://octodex.github.com/images/andycat.jpg",
  "https://octodex.github.com/images/notocat.jpg",
  "https://octodex.github.com/images/dodgetocat.jpg",
  "https://octodex.github.com/images/cloud.jpg",
  "https://octodex.github.com/images/scarletteocat.jpg",
  "https://octodex.github.com/images/poptocat.png",
  "https://octodex.github.com/images/jenktocat.jpg",
  "https://octodex.github.com/images/xtocat.jpg",
  "https://octodex.github.com/images/chellocat.jpg",
  "https://octodex.github.com/images/cherryontop-o-cat.png",
  "https://octodex.github.com/images/supportcat.png",
  "https://octodex.github.com/images/collabocats.jpg",
  "https://octodex.github.com/images/constructocat2.jpg",
  "https://octodex.github.com/images/total-eclipse-of-the-octocat.jpg",
  "https://octodex.github.com/images/pacman-ghosts.jpg",
  "https://octodex.github.com/images/okal-eltocat.jpg",
  "https://octodex.github.com/images/octoclark-kentocat.jpg",
  "https://octodex.github.com/images/agendacat.png",
  "https://octodex.github.com/images/ironcat.jpg",
  "https://octodex.github.com/images/inspectocat.jpg",
  "https://octodex.github.com/images/jean-luc-picat.jpg",
  "https://octodex.github.com/images/spocktocat.png",
  "https://octodex.github.com/images/wilson.jpg",
  "https://octodex.github.com/images/swagtocat.png",
  "https://octodex.github.com/images/drunktocat.jpg",
  "https://octodex.github.com/images/dolla-dolla-bill-yall.jpg",
  "https://octodex.github.com/images/hubot.jpg",
  "https://octodex.github.com/images/monroe.jpg",
  "https://octodex.github.com/images/trekkie.png",
  "https://octodex.github.com/images/octonaut.jpg",
  "https://octodex.github.com/images/bouncercat.png",
  "https://octodex.github.com/images/founding-father.jpg",
  "https://octodex.github.com/images/pythocat.png",
  "https://octodex.github.com/images/drupalcat.jpg",
  "https://octodex.github.com/images/socialite.jpg",
  "https://octodex.github.com/images/setuptocat.jpg",
  "https://octodex.github.com/images/repo.png",
  "https://octodex.github.com/images/forktocat.jpg",
  "https://octodex.github.com/images/benevocats.png",
  "https://octodex.github.com/images/scottocat.jpg",
  "https://octodex.github.com/images/puppeteer.png",
  "https://octodex.github.com/images/octobiwan.jpg",
  "https://octodex.github.com/images/class-act.png",
  "https://octodex.github.com/images/original.png"
]
